# Generated by Django 5.2.7 on 2025-10-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(help_text='Unique 1-letter airport code', max_length=1, unique=True),
        ),
    ]
